notifications:
  email:
    recipients:
      - nacos_dev@linux.alibaba.com
      - dev-nacos@googlegroups.com
  on_success: change
  on_failure: always

dist: xenial
sudo: required

language: java

jdk:
  - openjdk8
  - openjdk7

script:
